AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

require:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/WordArray:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 15

RSpec/MultipleExpectations:
  Description: Checks for number of expectations.
  Enabled: true
  Max: 6

Rails/BulkChangeTable:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false
