AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/**/*"

require:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  AllowedMethods:
    - change

Metrics/MethodLength:
  Enabled: true
  Max: 12
  AllowedMethods:
    - change

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MutableConstant:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 15

RSpec/MultipleExpectations:
  Description: Checks for number of expectations.
  Enabled: true
  Max: 6

Rails/BulkChangeTable:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false
